export const blob_1pleft = 'BLOB, the player to your left'
export const blob_1pright = 'BLOB, the player to your right'
export const blob_eachside = 'BLOB, one player on each side of you'
export const blob_2pleft = 'BLOB, the two players to your left'
export const blob_2pright = 'BLOB, the two players to your right'
export const blob_3pleft = 'BLOB, the three players to your left'
export const blob_3pright = 'BLOB, the three players to your right'
export const blob_4pleft = 'BLOB, the four players to your left'
export const blob_4pright = 'BLOB, the four players to your right'
export const blob_2eachside = 'BLOB, two players on each side of you'

export const blob_is_end = 'is now part of the Blob. Keep them and yourself alive in order to win.'
export const blob_are_end = 'are now part of the Blob. Keep them and yourself alive in order to win.'
