export const everyone_epic_intro_text = 'Prepare for an epic battle!'
export const everyone_card_text = 'EVERYONE, secretly view your Card.'
export const everyone_vote_text = 'Time is up. Everyone, 3, 2, 1... VOTE!'
export const everyone_mark_text = 'EVERYONE, secretly view your Mark.'
export const everyone_artifact_text = 'EVERYONE, anyone who has artifact, secretly view your artifact.'
