export const everyone_epic_intro = 'Prepare for an epic battle!'
export const everyone_card = 'EVERYONE, secretly view your Card.'
export const everyone_vote = 'Time is up. Everyone, 3, 2, 1... VOTE!'
export const everyone_mark = 'EVERYONE, secretly view your Mark.'
export const everyone_artifact = 'EVERYONE, anyone who has artifact, secretly view your artifact.'
