export const conjunction_and = 'and'
export const conjunction_or = 'or'

export const direction_left = 'left'
export const direction_right = 'right'

export const identifier_everyone = 'Everyone'
export const identifier_oddplayers = 'Odd Players'
export const identifier_evenplayers = 'Even Players'
export const identifier_higher = 'Any player with a number higher than yours'
export const identifier_lower = 'Any player with a number lower than yours'
export const identifier_any2 = 'Any two players'
export const identifier_any2even = 'Any two even players'
export const identifier_any2odd = 'Any two odd players'
export const identifier_any2higher = 'Any two players with a number higher than yours'
export const identifier_any2lower = 'Any two players with a number lower than yours'
export const identifier_2leftneighbors = 'The two players immediately to your left'
export const identifier_2rightneighbors = 'The two players immediately to your right'
export const identifier_any = 'Any player'
export const identifier_anyeven = 'Any even player'
export const identifier_anyodd = 'Any odd player'
export const identifier_oneneighbor = 'One of your neighbors'
export const identifier_center = 'The center'
export const identifier_leftneighbor = 'The neighbor on your left'
export const identifier_rightneighbor = 'The neighbor on your right'
export const identifier_bothneighbors = 'Both of your neighbors'
export const identifier_yourself = 'Yourself'

//TODO response player_1 = identifier_player1, ...
export const identifier_player1 = 'Player 1'
export const identifier_player2 = 'Player 2'
export const identifier_player3 = 'Player 3'
export const identifier_player4 = 'Player 4'
export const identifier_player5 = 'Player 5'
export const identifier_player6 = 'Player 6'
export const identifier_player7 = 'Player 7'
export const identifier_player8 = 'Player 8'
export const identifier_player9 = 'Player 9'
export const identifier_player10 = 'Player 10'
export const identifier_player11 = 'Player 11'
export const identifier_player12 = 'Player 12'

export const identifier_centerleft = 'Center Left'
export const identifier_centermiddle = 'Center Middle'
export const identifier_centerright = 'Center Right'

export const identifier_centerwolf = 'Center Wolf'
export const identifier_centervillain = 'Center Villain'
