export const joke_1 = '3... 2... 1... Vote! Just kidding.'
export const joke_2 = 'Be afraid, be very afraid.'
export const joke_3 = 'Grizzly ghouls from every tomb are closing in to seal your doom.'
export const joke_4 = 'He did the mash, it caught on in a flash.'
export const joke_5 = "Hold on a minute - you, with your eyes open! That's CHEATING."
export const joke_6 = 'Fun fact, hot dogs are 30% villager.'
export const joke_7 = 'I know who the werewolves are.'
export const joke_8 = 'I love this game - and I love all of you for playing it!'
export const joke_9 = 'I saw a werewolf with a Chinese menu in his hand.'
export const joke_10 = 'In one night, no one can hear you scream.'
export const joke_11 = "Instead of pointing at the player you wish to kill, point at a player you don't like."
export const joke_12 = 'Just when you thought it was safe to play another game of one night.'
export const joke_13 = 'Longest night evaaaarrr.'
export const joke_14 = "One more night, 'cause I can't wait forever."
export const joke_15 = 'One Night fever, One Night fever! We know how to do it.'
export const joke_16 = "One Night Ultimate Werewolf, and the world's your oyster."
export const joke_17 = 'Revved up like a deuce, another runner in One Night.'
export const joke_18 = 'The Resistance is futile! You will be assimilated into One Night!'
export const joke_19 = "They're heeeeeeeeeeeeerrrrreeeee."
export const joke_20 = 'Villagers are part of a nutritious breakfast.'
