export const buttons: Record<string, string> = {
  yes_button_label: 'YES',
  no_button_label: 'NO',
  even_button_label: 'EVEN',
  odd_button_label: 'ODD',
  '1_button_label': '1',
  '2_button_label': '2',
  '3_button_label': '3',
  '4_button_label': '4',
  '5_button_label': '5',
  '6_button_label': '6',
  '7_button_label': '7',
  '8_button_label': '8',
  '9_button_label': '9',
  '10_button_label': '10',
  '11_button_label': '11',
  '12_button_label': '12',
  pause_button_label: 'PAUSE',
  pause_button_alt_label: 'RESUME',
  stop_button_label: 'STOP',
  votenow_button_label: 'Vote Now!',
  reset_game_label: 'RESET',
  play_game_text: 'PLAY ',
  start_game_label: 'START',
}
