export const identifier = {
  identifier_everyone_text: 'Everyone',
  identifier_oddplayers_text: 'Odd Players',
  identifier_evenplayers_text: 'Even Players',
  identifier_higher_text: 'Any player with a number higher than yours',
  identifier_lower_text: 'Any player with a number lower than yours',
  identifier_any2_text: 'Any two players',
  identifier_any2even_text: 'Any two even players',
  identifier_any2odd_text: 'Any two odd players',
  identifier_any2higher_text: 'Any two players with a number higher than yours',
  identifier_any2lower_text: 'Any two players with a number lower than yours',
  identifier_2leftneighbors_text: 'The two players immediately to your left',
  identifier_2rightneighbors_text: 'The two players immediately to your right',
  identifier_any_text: 'Any player',
  identifier_anyeven_text: 'Any even player',
  identifier_anyodd_text: 'Any odd player',
  identifier_oneneighbor_text: 'One of your neighbors',
  identifier_center_text: 'The center',
  identifier_leftneighbor_text: 'The neighbor on your left',
  identifier_rightneighbor_text: 'The neighbor on your right',
  identifier_bothneighbors_text: 'Both of your neighbors',
  identifier_yourself_text: 'Yourself',
}

export const identifier_player = {
  identifier_player1_text: 'Player 1',
  identifier_player2_text: 'Player 2',
  identifier_player3_text: 'Player 3',
  identifier_player4_text: 'Player 4',
  identifier_player5_text: 'Player 5',
  identifier_player6_text: 'Player 6',
  identifier_player7_text: 'Player 7',
  identifier_player8_text: 'Player 8',
  identifier_player9_text: 'Player 9',
  identifier_player10_text: 'Player 10',
  identifier_player11_text: 'Player 11',
  identifier_player12_text: 'Player 12',
}
