export const roles = {
  role_alien: 'ALIEN',
  role_aliens: 'ALIENS',
  role_alphawolf: 'ALPHA WOLF',
  role_annoyinglad: 'ANNOYING LAD',
  role_apprenticeassassin: 'APPRENTICE ASSASSIN',
  role_apprenticetanner: 'APPRENTICE TANNER',
  role_apprenticeseer: 'APPRENTICE SEER',
  role_assassin: 'ASSASSIN',
  role_auraseer: 'AURA SEER',
  role_beholder: 'BEHOLDER',
  role_blob: 'BLOB',
  role_bodyguard: 'BODYGUARD',
  role_bodysnatcher: 'BODYSNATCHER',
  role_copycat: 'COPYCAT',
  role_cow: 'COW',
  role_cupid: 'CUPID',
  role_curator: 'CURATOR',
  role_cursed: 'CURSED',
  role_detector: 'DETECTOR',
  role_defenderer: 'DEFENDERER',
  role_diseased: 'DISEASED',
  role_doppelganger: 'DOPPELGANGER',
  role_dreamwolf: 'DREAM WOLF',
  role_drpeeker: 'DR. PEEKER',
  role_drunk: 'DRUNK',
  role_empath: 'EMPATH',
  role_everyone: 'EVERYONE',
  role_evilometer: 'EVILOMETER',
  role_exposer: 'EXPOSER',
  role_familyman: 'FAMILY MAN',
  role_flipper: 'FLIPPER',
  role_gremlin: 'GREMLIN',
  role_groob: 'GROOB',
  role_groobzerb: 'GROOB AND ZERB',
  role_henchman: 'HENCHMAN #7',
  role_hunter: 'HUNTER',
  role_innocentbystander: 'INNOCENT BYSTANDER',
  role_instigator: 'INSTIGATOR',
  role_insomniac: 'INSOMNIAC',
  role_intern: 'INTERN',
  role_leader: 'LEADER',
  role_madscientist: 'MAD SCIENTIST',
  role_marksman: 'MARKSMAN',
  role_mason: 'MASON',
  role_masons: 'MASONS',
  role_mirrorman: 'MIRROR MAN',
  role_minion: 'MINION',
  role_mortician: 'MORTICIAN',
  role_mysticwolf: 'MYSTIC WOLF',
  role_nostradamus: 'NOSTRADAMUS',
  role_oracle: 'ORACLE',
  role_paranormalinvestigator: 'P.I.',
  role_pickpocket: 'PICKPOCKET',
  role_priest: 'PRIEST',
  role_prince: 'PRINCE',
  role_psychic: 'PSYCHIC',
  role_rapscallion: 'RAPSCALLION',
  role_rascal: 'RASCAL',
  role_renfield: 'RENFIELD',
  role_revealer: 'REVEALER',
  role_ricochetrhino: 'RICOCHET RHINO',
  role_robber: 'ROBBER',
  role_roleretriever: 'ROLE RETRIEVER',
  role_selfawarenessgirl: 'SELF-AWARENESS GIRL',
  role_sentinel: 'SENTINEL',
  role_seer: 'SEER',
  role_squire: 'SQUIRE',
  role_supervillains: 'SUPER VILLAINS',
  role_synthetic: 'SYNTHETIC ALIEN',
  role_switcheroo: 'SWITCHEROO',
  role_temptress: 'TEMPTRESS',
  role_thecount: 'THE COUNT',
  role_themaster: 'THE MASTER',
  role_thesponge: 'THE SPONGE',
  role_thing: 'THING',
  role_tanner: 'TANNER',
  role_troublemaker: 'TROUBLEMAKER',
  role_vampire: 'VAMPIRE',
  role_vampires: 'VAMPIRES',
  role_villageidiot: 'VILLAGE IDIOT',
  role_villager: 'VILLAGER',
  role_voodoolou: 'VOODOO LOU',
  role_werewolf: 'WEREWOLF',
  role_werewolves: 'WEREWOLVES',
  role_windywendy: 'WINDY WENDY',
  role_witch: 'WITCH',
  role_zerb: 'ZERB',
}
