export const wining_role: Record<string, string> = {
  wining_village_or_hero_team: 'You can win if any one dies from',
  wining_werewolf_team: 'You can win if no werewolf on the werewolf team dies',
  wining_minion_team: 'You can win if you survive, and any one else dies',
  wining_squire_team: 'You can win if you survive, and any one else dies',
  wining_vampire_team: 'You can win if no vampire on the vampire team dies',
  wining_vampire_master_team: ' or any vampire votes for you',
  wining_alien_team: 'You can win if no alien on the alien team dies',
  wining_villain_team: 'You can win if no villain on the villain team dies',
  wining_tanner_team: 'You can win if you die',
  wining_apprenticetanner_team: 'You can win if anyone on tanner team dies',
  wining_apprenticeassassin_team: 'You can win if the Assassin does get killed',
  wining_assassin_team: 'You can win if the owner of the Mark of Assassin does get killed',
  wining_groob_team: 'You can win if Zerb does get killed',
  wining_zerb_team: 'You can win if Groob does get killed',
  wining_leader_team: 'You can win if Groob and Zerb survive',
  wining_blob_team: 'You can win if everyone part of you survive',
  wining_mortician_team: 'You can win if anyone from your neighbors gets killed',
  wining_synthetic_team: 'You can win if you die',
  wining_mad_team: 'You can win if Mad Scientist gets killed',
  wining_oracle_team: 'You can win if you survive',

  wining_vs_werewolf: ' the werewolf team',
  wining_vs_vampire: ' the vampire team',
  wining_vs_alien: ' the alien team',
  wining_vs_villain: ' the villain team',
  wining_vs_village_epic: ' 2 other "badguy" teams',
  wining_vs_badguy_epic: ', and 1 from other "badguy" teams',
  wining_vs_nopresent: '. If no present, then everyone must to survive',

  wining_vs_you: ' even if you dies',
  wining_vs_hunter: " or in case of Hunter's death, the Hunter doesn't point at you",
  wining_vs_ricochetrhino: " or in case of Ricochet Rhino gets most votes, Ricochet Rhino doesn't point at you",
  wining_vs_tanner: ', and Tanner(s) stay alive',
  wining_vs_minion: ', even if Minion dies',
  wining_vs_bodyguard: ', or the Bodyguard does points at you',
  wining_vs_defenderer: ', or the Defender-er does points at you',
  wining_vs_leader: ', or all vampires does points at Leader',
  wining_vs_madscientist: ', and Mad Scientist(s) stay alive',

  wining_vs_oracle: 'You can win if Oracle gets killed, if no Oracle, everyone must survive',

  wining_cursed: "You can win with the village team, or in case of any werewolf's vote, you can win with werewolf team",
  wining_windywendy: "You can win with the hero team, or in case of any villain's vote, you can win with villain team",
  wining_prince: 'You can not die',
  wining_sponge: 'You can not die',

  //mark override card, artifact override mark or card
  wining_with_vampire_token: 'You can win with the vampire team, even if you get killed',
  wining_with_love_token: ", or the owner of the Mark of Love doesn't get killed",
  wining_with_traitor_token: 'You can win, if anyone from your team gets killed, and you survive',
  wining_with_alien_token: 'You can win with the alien team, even if you get killed',
  wining_with_village_token: 'You can win with the village team, even if you get killed',
  wining_with_werewolf_token: 'You can win with the werewolf team, even if you get killed',
  wining_vs_disease_token: ", and the owner of the Mark of Disease doesn't point at you"
}
