export const KEEP_ALIVE = 'KEEP_ALIVE'
export const UPDATE_SELECT = 'UPDATE_SELECT'
export const RESET = 'RESET'
export const PLAY_GAME = 'PLAY_GAME'
export const NEWBIE = 'NEWBIE'
export const JOIN_ROOM = 'JOIN_ROOM'
export const LEAVE_ROOM = 'LEAVE_ROOM'
export const HYDRATE_SELECT = 'HYDRATE_SELECT'

export const CARD_DESELECT = 'CARD_DESELECT'
export const CARD_SELECT = 'CARD_SELECT'
