export const NEWBIE = 'NEWBIE'
export const RELOAD = 'RELOAD'
export const KEEP_ALIVE = 'KEEP_ALIVE'
export const RESET = 'RESET'
export const DEAL = 'DEAL'
export const REDIRECT = 'REDIRECT'
export const SCENE = 'SCENE'
export const MESSAGE = 'MESSAGE'
export const RESULT = 'RESULT'

export const JOIN_ROOM = 'JOIN_ROOM'
export const JOIN_VOTE = 'JOIN_VOTE'

export const READY = 'READY'
export const READY_VOTE = 'READY_VOTE'

export const ARRIVE_LOBBY = 'ARRIVE_LOBBY'
export const ARRIVE_ROOM = 'ARRIVE_ROOM'
export const ARRIVE_TABLE = 'ARRIVE_TABLE'
export const ARRIVE_GAME = 'ARRIVE_GAME'
export const ARRIVE_VOTE = 'ARRIVE_VOTE'
export const ARRIVE_COUNCIL = 'ARRIVE_COUNCIL'
export const ARRIVE_VERDICT = 'ARRIVE_VERDICT'

export const HYDRATE_LOBBY = 'HYDRATE_LOBBY'
export const HYDRATE_ROOM = 'HYDRATE_ROOM'
export const HYDRATE_TABLE = 'HYDRATE_TABLE'
export const HYDRATE_READY = 'HYDRATE_READY'
export const HYDRATE_GAME = 'HYDRATE_GAME'
export const HYDRATE_SCENE = 'HYDRATE_SCENE'
export const HYDRATE_VOTE = 'HYDRATE_VOTE'
export const HYDRATE_GUESS = 'HYDRATE_GUESS'
export const HYDRATE_COUNCIL = 'HYDRATE_COUNCIL'

export const UPDATE_ROOM = 'UPDATE_ROOM'
export const UPDATE_TABLE = 'UPDATE_TABLE'
export const UPDATE_GAME = 'UPDATE_GAME'
export const UPDATE_VOTE = 'UPDATE_VOTE'
export const UPDATE_GUESS = 'UPDATE_GUESS'

export const LEAVE_ROOM = 'LEAVE_ROOM'
export const LEAVE_GAME = 'LEAVE_GAME'
export const LEAVE_VOTE = 'LEAVE_VOTE'

export const START_GAME = 'START_GAME'
export const END_GAME = 'END_GAME'
export const STOP_GAME = 'STOP_GAME'
export const PAUSE_GAME = 'PAUSE_GAME'

export const START_VOTE = 'START_VOTE'
export const VOTE = 'VOTE'
export const VOTE_ACCEPTED = 'VOTE_ACCEPTED'

export const VAMPIRES = 'VAMPIRES'
export const ALIENS = 'ALIENS'
export const EMPATH = 'EMPATH'
export const DOPPELGÄNGER_EMPATH = 'DOPPELGÄNGER_EMPATH'
