export const NEWBIE = 'NEWBIE'
export const KEEP_ALIVE = 'KEEP_ALIVE'
export const JOIN_ROOM = 'JOIN_ROOM'
export const LEAVE_ROOM = 'LEAVE_ROOM'

export const ARRIVE_LOBBY = 'ARRIVE_LOBBY'
export const ARRIVE_ROOM = 'ARRIVE_ROOM'
export const ARRIVE_GAME_TABLE = 'ARRIVE_GAME_TABLE'
export const ARRIVE_GAME_PLAY = 'ARRIVE_GAME_PLAY'
export const ARRIVE_GAME_VOTE = 'ARRIVE_GAME_VOTE'

export const HYDRATE_LOBBY = 'HYDRATE_LOBBY'
export const HYDRATE_ROOM = 'HYDRATE_ROOM'
export const HYDRATE_GAME_TABLE = 'HYDRATE_GAME_TABLE'
export const HYDRATE_GAME_PLAY = 'HYDRATE_GAME_PLAY'
export const HYDRATE_GAME_VOTE = 'HYDRATE_GAME_VOTE'

export const UPDATE_ROOM = 'UPDATE_ROOM'
export const RESET = 'RESET'
export const TO_GAME_TABLE = 'TO_GAME_TABLE'
export const LEAVE_TABLE = 'LEAVE_TABLE'
export const UPDATE_GAME_TABLE = 'UPDATE_GAME_TABLE'
export const READY = 'READY'
export const REDIRECT = 'REDIRECT'
export const START_GAME = 'START_GAME'

export const STAGES = {
  LOBBY: 'LOBBY',
  ROOM: 'ROOM',
  GAME_TABLE: 'GAME_TABLE',
  GAME_PLAY: 'GAME_PLAY',
  GAME_VOTE: 'GAME_VOTE',
}
