export const labels = ['Player1', 'Player2', 'Player3', 'Player4', 'Player5', 'Player6', 'Player7', 'Player8', 'Player9', 'Player10', 'Player11', 'Player12', 'CenterLeft', 'CenterMiddle', 'CenterRight', 'CenterWolf', 'CenterVillain']

export const role_map: Record<number, string> = {
  1: 'Doppelganger',
  2: 'Drunk',
  3: 'Hunter',
  4: 'Insomniac',
  5: 'Mason1',
  6: 'Mason2',
  7: 'Minion',
  8: 'Robber',
  9: 'Seer',
  10: 'Tanner',
  11: 'Troublemaker',
  12: 'Villager1',
  13: 'Villager2',
  14: 'Villager3',
  15: 'Werewolf1',
  16: 'Werewolf2',
  17: 'Alpha Wolf',
  18: 'Apprentice Seer',
  19: 'Bodyguard',
  20: 'Curator',
  21: 'Dreamwolf',
  22: 'Mysticwolf',
  23: 'Paranormal Investigator',
  24: 'Revealer',
  25: 'Sentinel',
  26: 'Village_Idiot',
  27: 'Witch',
  28: 'Apprentice Assassin',
  29: 'Assassin',
  30: 'Copycat',
  31: 'Cupid',
  32: 'Diseased',
  33: 'Gremlin',
  34: 'Instigator',
  35: 'Marksman',
  36: 'Pickpocket',
  37: 'Priest',
  38: 'Renfield',
  39: 'The Count',
  40: 'The Master',
  41: 'Vampire',
  42: 'Alien1',
  43: 'Alien2',
  44: 'Blob',
  45: 'Cow',
  46: 'Exposer',
  47: 'Groob',
  48: 'Leader',
  49: 'Mortician',
  50: 'Oracle',
  51: 'Psychic',
  52: 'Rascal',
  53: 'Synthetic Alien',
  54: 'Zerb',
  55: 'Annoying Lad',
  56: 'Detector',
  57: 'Dr. Peeker',
  58: 'Evilometer',
  59: 'Flipper',
  60: 'Henchman #7',
  61: 'Innocent Bystander1',
  62: 'Intern',
  63: 'Mad Scientist',
  64: 'Mirror Man',
  65: 'Rapscallion',
  66: 'Role Retriever',
  67: 'Self-Awareness Girl',
  68: 'Switcheroo',
  69: 'Temptress',
  70: 'Voodoo Lou',
  71: 'Apprentice Tanner',
  72: 'Aura Seer',
  73: 'Beholder',
  74: 'Body Snatcher',
  75: 'Cursed',
  76: 'Defenderer',
  77: 'Empath',
  78: 'Family Man',
  79: 'Innocent Bystander2',
  80: 'Nostradamus',
  81: 'Prince',
  82: 'Ricochet Rhino',
  83: 'Squire',
  84: 'The Sponge',
  85: 'Thing',
  86: 'Windy Wendy'
}
