export { default as first_votes } from './1st_votes.png'
export { default as second_votes } from './2nd_votes.png'

export { default as artifact_back } from './artifact_back.png'
export { default as mark_back } from './mark_back.png'
export { default as marks_place } from './marks_place.png'

export { default as shield } from './shield.png'

export { default as alien_artifact } from './alien_artifact.png'
export { default as bow_of_the_hunter } from './bow_of_the_hunter.png'
export { default as brand_of_the_villager } from './brand_of_the_villager.png'
export { default as claw_of_the_werewolf } from './claw_of_the_werewolf.png'
export { default as cloak_of_the_prince } from './cloak_of_the_prince.png'
export { default as cudgel_of_the_tanner } from './cudgel_of_the_tanner.png'
export { default as dagger_of_the_traitor } from './dagger_of_the_traitor.png'
export { default as mask_of_muting } from './mask_of_muting.png'
export { default as mist_of_the_vampire } from './mist_of_the_vampire.png'
export { default as shroud_of_shame } from './shroud_of_shame.png'
export { default as sword_of_the_bodyguard } from './sword_of_the_bodyguard.png'
export { default as void_of_nothingness } from './void_of_nothingness.png'

export { default as mark_of_assassin } from './mark_of_assassin.png'
export { default as mark_of_clarity } from './mark_of_clarity.png'
export { default as mark_of_disease } from './mark_of_disease.png'
export { default as mark_of_fear } from './mark_of_fear.png'
export { default as mark_of_love } from './mark_of_love.png'
export { default as mark_of_the_bat } from './mark_of_the_bat.png'
export { default as mark_of_traitor } from './mark_of_traitor.png'
export { default as mark_of_vampire } from './mark_of_vampire.png'
