export const losing_role: Record<string, string> = {
  losing_village_or_hero_team: 'You can lose if no one dies from',
  losing_werewolf_tem: 'You can lose if any werewolf on the werewolf team dies',
  losing_minion_tem: 'You can lose if you die',
  losing_squire_tem: 'You can lose if you die',
  losing_vampire_team: 'You can lose if any vampire on the vampire team dies',
  losing_vampire_master_team: ' and no vampire votes for you',
  losing_alien_team: 'You can lose if any alien on the alien team dies',
  losing_villain_team: 'You can lose if any villain on the villain team dies',
  losing_tanner_team: 'You can lose if you stay alive',
  losing_apprenticetanner_team: 'You can lose if everyone on tanner team survive',
  losing_apprenticeassassin_team: 'You can lose if the Assassin survive',
  losing_assassin_team: 'You can lose if the owner of the Mark of Assassin survive',
  losing_groob_team: 'You can lose if Zerb survives',
  losing_zerb_team: 'You can lose if Groob survives',
  losing_leader_team: 'You can lose if Groob or Zerb gets killed',
  losing_blob_team: 'You can lose if anyone part of you gets killed',
  losing_mortician_team: 'You can lose if both of your neighbors survive',
  losing_synthetic_team: 'You can lose if you survive',
  losing_mad_team: 'You can lose if Mad Scientist survive',
  losing_oracle_team: 'You can lose if anyone on oracle team dies',

  losing_vs_you: ' even if you survive',
  losing_vs_werewolf: ' the werewolf team',
  losing_vs_vampire: ' the vampire team',
  losing_vs_alien: ' the alien team',
  losing_vs_villain: ' the villain team',
  losing_vs_village_epic: ' 2 other teams',
  losing_vs_nopresent: '. If no present, and anyone gets killed from your team',

  losing_vs_hunter: " or in case of Hunter's death, the Hunter does point at you",
  losing_vs_ricochetrhino: ' or in case of Ricochet Rhino gets most votes, Ricochet Rhino does point at you',
  losing_vs_tanner: ' or Tanner dies',
  losing_vs_madscientist: ', or Mad Scientist(s) dies',

  losing_vs_oracle: 'You can lose if Oracle survive',

  //mark override card, artifact override mark or card
  losing_with_vampire_token: 'You can lose with the vampire team, even if you stay alive',
  losing_with_love_token: ", or the owner of the Mark of Love doesn't stay alive",
  losing_with_traitor_token: "You can lose, if anyone from your team doesn't get killed, or you die",
  losing_with_alien_token: 'You can lose with the alien team, even if you stay alive',
  losing_with_village_token: 'You can lose with the village team, even if you stay alive',
  losing_with_werewolf_token: 'You can lose with the werewolf team, even if you stay alive'
}
