import {
  AerialIcon,
  AlienIcon,
  AlienhandIcon,
  AlienstareIcon,
  ArtifactedIcon,
  AssassinIcon,
  AwesomeIcon,
  BabyAlienIcon,
  BatIcon,
  BearIcon,
  BlindIcon,
  BlobIcon,
  BulbIcon,
  ClarityIcon,
  ClawIcon,
  ClosedIcon,
  ClosingIcon,
  CoffinIcon,
  ConnectingIcon,
  CopyIcon,
  CowIcon,
  CupidIcon,
  DetectorIcon,
  DiseasedIcon,
  DogIcon,
  DreamwolfIcon,
  DressIcon,
  DrunkIcon,
  EmpathIcon,
  EvilhandIcon,
  FamilyIcon,
  FangIcon,
  FearIcon,
  FriendIcon,
  GremlinIcon,
  GroobzerbIcon,
  IdcardIcon,
  InteractionIcon,
  InvestigatorIcon,
  JestIcon,
  LikeIcon,
  LonelyIcon,
  LoverIcon,
  MadIcon,
  MasonIcon,
  MorticianIcon,
  MuteIcon,
  MysticIcon,
  NiceIcon,
  NightIcon,
  NightvisionIcon,
  NostradamusIcon,
  OpenIcon,
  OracleIcon,
  PeekerIcon,
  PrankIcon,
  PrettyIcon,
  PsychicIcon,
  RobberIcon,
  SecretIcon,
  SeerIcon,
  SelectIcon,
  SentinelIcon,
  ShieldedIcon,
  SmellIcon,
  SpyIcon,
  SusIcon,
  SwapIcon,
  TannerIcon,
  TapIcon,
  TargetIcon,
  ThecountIcon,
  ThinkIcon,
  ThumbIcon,
  TraitorIcon,
  TrophyIcon,
  UfoIcon,
  UninstantiatedIcon,
  VampireIcon,
  VillainIcon,
  VoodooIcon,
  WerewolfIcon,
  WitchIcon,
} from 'assets'
import { StyledIcon } from './Icon.styles'
import { IconType, IconProps } from './Icon.types'

export const Icons: Record<
  IconType,
  React.FC<React.SVGProps<SVGSVGElement>>
> = {
  aerial: AerialIcon,
  alien: AlienIcon,
  alienhand: AlienhandIcon,
  alienstare: AlienstareIcon,
  artifacted: ArtifactedIcon,
  assassin: AssassinIcon,
  awesome: AwesomeIcon,
  babyalien: BabyAlienIcon,
  bat: BatIcon,
  bear: BearIcon,
  blind: BlindIcon,
  blob: BlobIcon,
  bulb: BulbIcon,
  clarity: ClarityIcon,
  claw: ClawIcon,
  closed: ClosedIcon,
  closing: ClosingIcon,
  coffin: CoffinIcon,
  connecting: ConnectingIcon,
  copy: CopyIcon,
  cow: CowIcon,
  cupid: CupidIcon,
  detector: DetectorIcon,
  diseased: DiseasedIcon,
  dog: DogIcon,
  dreamwolf: DreamwolfIcon,
  dress: DressIcon,
  drunk: DrunkIcon,
  empath: EmpathIcon,
  evilhand: EvilhandIcon,
  family: FamilyIcon,
  fang: FangIcon,
  fear: FearIcon,
  friend: FriendIcon,
  gremlin: GremlinIcon,
  groobzerb: GroobzerbIcon,
  idcard: IdcardIcon,
  interaction: InteractionIcon,
  investigator: InvestigatorIcon,
  jest: JestIcon,
  like: LikeIcon,
  lonely: LonelyIcon,
  lover: LoverIcon,
  mad: MadIcon,
  mason: MasonIcon,
  mortician: MorticianIcon,
  mute: MuteIcon,
  mystic: MysticIcon,
  nice: NiceIcon,
  night: NightIcon,
  nightvision: NightvisionIcon,
  nostradamus: NostradamusIcon,
  open: OpenIcon,
  oracle: OracleIcon,
  peeker: PeekerIcon,
  prank: PrankIcon,
  pretty: PrettyIcon,
  psychic: PsychicIcon,
  robber: RobberIcon,
  secret: SecretIcon,
  seer: SeerIcon,
  select: SelectIcon,
  sentinel: SentinelIcon,
  shielded: ShieldedIcon,
  smell: SmellIcon,
  spy: SpyIcon,
  sus: SusIcon,
  swap: SwapIcon,
  tanner: TannerIcon,
  tap: TapIcon,
  target: TargetIcon,
  thecount: ThecountIcon,
  think: ThinkIcon,
  thumb: ThumbIcon,
  traitor: TraitorIcon,
  trophy: TrophyIcon,
  ufo: UfoIcon,
  uninstantiated: UninstantiatedIcon,
  vampire: VampireIcon,
  villain: VillainIcon,
  voodoo: VoodooIcon,
  werewolf: WerewolfIcon,
  witch: WitchIcon,
}

export const Icon: React.FC<IconProps> = ({ iconName, size }) => (
  <StyledIcon as={Icons[iconName]} size={size} />
)
