export const identifier_everyone_text = 'Everyone'
export const identifier_oddplayers_text = 'Odd Players'
export const identifier_evenplayers_text = 'Even Players'
export const identifier_higher_text =
  'Any player with a number higher than yours'
export const identifier_lower_text = 'Any player with a number lower than yours'
export const identifier_any2_text = 'Any two players'
export const identifier_any2even_text = 'Any two even players'
export const identifier_any2odd_text = 'Any two odd players'
export const identifier_any2higher_text =
  'Any two players with a number higher than yours'
export const identifier_any2lower_text =
  'Any two players with a number lower than yours'
export const identifier_2leftneighbors_text =
  'The two players immediately to your left'
export const identifier_2rightneighbors_text =
  'The two players immediately to your right'
export const identifier_any_text = 'Any player'
export const identifier_anyeven_text = 'Any even player'
export const identifier_anyodd_text = 'Any odd player'
export const identifier_oneneighbor_text = 'One of your neighbors'
export const identifier_center_text = 'The center'
export const identifier_leftneighbor_text = 'The neighbor on your left'
export const identifier_rightneighbor_text = 'The neighbor on your right'
export const identifier_bothneighbors_text = 'Both of your neighbors'
export const identifier_yourself_text = 'Yourself'

//TODO response player_1 = identifier_player1_text, ...
export const identifier_player1_text = 'Player 1'
export const identifier_player2_text = 'Player 2'
export const identifier_player3_text = 'Player 3'
export const identifier_player4_text = 'Player 4'
export const identifier_player5_text = 'Player 5'
export const identifier_player6_text = 'Player 6'
export const identifier_player7_text = 'Player 7'
export const identifier_player8_text = 'Player 8'
export const identifier_player9_text = 'Player 9'
export const identifier_player10_text = 'Player 10'
export const identifier_player11_text = 'Player 11'
export const identifier_player12_text = 'Player 12'
