export const joke_1_text = '3... 2... 1... Vote! Just kidding.'
export const joke_2_text = 'Be afraid, be very afraid.'
export const joke_3_text = 'Grizzly ghouls from every tomb are closing in to seal your doom.'
export const joke_4_text = 'He did the mash, it caught on in a flash.'
export const joke_5_text = "Hold on a minute - you, with your eyes open! That's CHEATING."
export const joke_6_text = 'Fun fact, hot dogs are 30% villager.'
export const joke_7_text = 'I know who the werewolves are.'
export const joke_8_text = 'I love this game - and I love all of you for playing it!'
export const joke_9_text = 'I saw a werewolf with a Chinese menu in his hand.'
export const joke_10_text = 'In one night, no one can hear you scream.'
export const joke_11_text = "Instead of pointing at the player you wish to kill, point at a player you don't like."
export const joke_12_text = 'Just when you thought it was safe to play another game of one night.'
export const joke_13_text = 'Longest night evaaaarrr.'
export const joke_14_text = "One more night, 'cause I can't wait forever."
export const joke_15_text = 'One Night fever, One Night fever! We know how to do it.'
export const joke_16_text = "One Night Ultimate Werewolf, and the world's your oyster."
export const joke_17_text = 'Revved up like a deuce, another runner in One Night.'
export const joke_18_text = 'The Resistance is futile! You will be assimilated into One Night!'
export const joke_19_text = "They're heeeeeeeeeeeeerrrrreeeee."
export const joke_20_text = 'Villagers are part of a nutritious breakfast.'
